### ISSUE TITLE
Incorrect usage of Pie charts

### ISSUE THREAD

**Issue by mtorchiano** [polito-se2-2020-team6/PULSeBS#57]
Concerning story 10, when summary data is reported, a pie chart is used in a wrong way.

* pie charts are used to represent part-to-whole relationships. If the values represented by the slices of the chart are not parts of a unique whole, then the pie chart is misleading and impossible to understand.
    - in this specific case different values with their Std Deviation **do not** form a whole, so they cannot be represented with a pie chart
* the use of a legend forces the observer of the chart to move the sight back and forth between the slices and the legend, this makes the understanding of the chart tiresome, moreover the identification and distinction of more than 4 different colors is difficult for human perception system. Therefore when you use a pie chart you should label directly each slice and avoid separate legend.

**Comment by mosTavassoli** [comment]
Dear Prof Torchiano,

Your issue is useful and informative. I changed your mentioned chart, Pie Chart into the table.
I appreciate your attention and full description.
Thank you.
